name: PR Hotfix

on:
  pull_request:
    branches:
      - hotfix
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-hotfix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean_pr_hotfix:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      HEAD_SHA: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Cherry-pick squashed hotfix release commit to main
        shell: bash
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          echo "Cherry-pick squashed hotfix release commit to main"
    
      - name: Delete hotfix branch
        shell: bash
        run: |
          echo "Delete hotfix branch"
