name: Release Please

on:
  create:
    branches:
      - 'release/**'
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - .release-please-manifest.json
      - CHANGELOG.md
      - composer.json
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
       # for configuration see https://github.com/google-github-actions/release-please-action
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: php
          # By default, Release Please uses the built-in GITHUB_TOKEN secret. However, all resources created by
          # release-please (release tag or release pull request) will not trigger future GitHub actions workflows, and
          # workflows normally triggered by release.created events will also not run.
          # Thus, we need to use a personal access token (PAT).
          token: ${{ secrets.GITHUB_TOKEN }} # FIXME
          target-branch: ${{ env.BRANCH_NAME }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  deploy-helm-prd:
    needs: release-please
    # After merging the release PR, a release tag will be created
    if:  ${{ needs.release-please.outputs.release_created }} # contains(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest
    steps:
      - name: Prepare vars for build
        shell: bash
        run: |
          echo "TODO: update prod helm charts"
